
CREATE TABLE IF NOT EXISTS ZeroTrustAuthenToken ( 
   id INTEGER PRIMARY KEY,
   ChipNum INTEGER NOT NULL,
   CH_LLK BLOB NOT NULL UNIQUE,
   n_x BLOB NOT NULL,
   Chlng_num INTEGER NOT NULL, 
   STATUS INTEGER NOT NULL
   );

CREATE UNIQUE INDEX ZTAT_ID_index ON ZeroTrustAuthenToken (ID);
